enum RoleTypexxx {
  SUPER_ADMIN_PDHS,
  ADMIN_PDHS,
  SUPER_ADMIN_RDHS,
  ADMIN_RDHS,
  SUPER_ADMIN_INSTITUTE,
  ADMIN_INSTITUTE,
  VIEWER_PDHS,
  VIEWER_RDHS,
  VIEWER_INSTITUTE,
  STORE_KEEPER,
  BIOMEDICAL_TECHNICIAN,
  PROCUREMENT_OFFICER,
  INSTITUTION_USER
}