export enum ScopeType {
  PDHS = 'PDHS', RDHS = 'RDHS', INSTITUTE = 'INSTITUTE',
}
export enum RoleType {
  SUPER_ADMIN_PDHS = 'SUPER_ADMIN_PDHS',
  ADMIN_PDHS = 'ADMIN_PDHS',
  VIEWER_PDHS = 'VIEWER_PDHS',
  SUPER_ADMIN_RDHS = 'SUPER_ADMIN_RDHS',
  ADMIN_RDHS = 'ADMIN_RDHS',
  VIEWER_RDHS = 'VIEWER_RDHS',
  SUPER_ADMIN_INSTITUTE = 'SUPER_ADMIN_INSTITUTE',
  ADMIN_INSTITUTE = 'ADMIN_INSTITUTE',
  VIEWER_INSTITUTE = 'VIEWER_INSTITUTE',
  STORE_KEEPER = 'STORE_KEEPER',
  BIOMEDICAL_TECHNICIAN = 'BIOMEDICAL_TECHNICIAN',
  PROCUREMENT_OFFICER = 'PROCUREMENT_OFFICER',
  INSTITUTION_USER = 'INSTITUTION_USER'
}

export const SCOPE_ROLES: Record<ScopeType, RoleType[]> = {
  [ScopeType.PDHS]: [
    RoleType.SUPER_ADMIN_PDHS, RoleType.ADMIN_PDHS, RoleType.VIEWER_PDHS,
    RoleType.BIOMEDICAL_TECHNICIAN, RoleType.PROCUREMENT_OFFICER, RoleType.STORE_KEEPER,
  ],
  [ScopeType.RDHS]: [
    RoleType.SUPER_ADMIN_RDHS, RoleType.ADMIN_RDHS, RoleType.VIEWER_RDHS,
  ],
  [ScopeType.INSTITUTE]: [
    RoleType.SUPER_ADMIN_INSTITUTE, RoleType.ADMIN_INSTITUTE,
    RoleType.INSTITUTION_USER, RoleType.VIEWER_INSTITUTE,
  ],
};

export enum Permission {

  INSTITUTE_VIEW = 'INSTITUTE_VIEW',
  INSTITUTE_CREATE = 'INSTITUTE_CREATE',
  INSTITUTE_UPDATE = 'INSTITUTE_UPDATE',
  INSTITUTE_DELETE = 'INSTITUTE_DELETE',

  INVENTORY_VIEW = 'INVENTORY_VIEW',
  INVENTORY_CREATE = 'INVENTORY_CREATE',
  INVENTORY_UPDATE = 'INVENTORY_UPDATE',
  INVENTORY_DELETE = 'INVENTORY_DELETE',

  EQUIPMENT_VIEW = 'EQUIPMENT_VIEW',
  EQUIPMENT_CREATE = 'EQUIPMENT_CREATE',
  EQUIPMENT_UPDATE = 'EQUIPMENT_UPDATE',
  EQUIPMENT_ASSIGN = 'EQUIPMENT_ASSIGN',
  EQUIPMENT_DISPOSE = 'EQUIPMENT_DISPOSE',
  EQUIPMENT_DELETE = 'EQUIPMENT_DELETE',

  REPAIR_REQUEST_VIEW = 'REPAIR_REQUEST_VIEW',
  REPAIR_REQUEST_CREATE = 'REPAIR_REQUEST_CREATE',
  REPAIR_REQUEST_UPDATE = 'REPAIR_REQUEST_UPDATE',

  WORK_ORDER_VIEW = 'WORK_ORDER_VIEW',
  WORK_ORDER_ASSIGN = 'WORK_ORDER_ASSIGN',
  WORK_ORDER_COMPLETE = 'WORK_ORDER_COMPLETE',

  PROCUREMENT_VIEW = 'PROCUREMENT_VIEW',
  PROCUREMENT_CREATE = 'PROCUREMENT_CREATE',
  PROCUREMENT_APPROVE = 'PROCUREMENT_APPROVE',

  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  PERMISSION_VIEW = 'PERMISSION_VIEW',
  PERMISSION_CREATE = 'PERMISSION_CREATE',
  PERMISSION_CREATE_TEMPORARY = 'PERMISSION_CREATE_TEMPORARY',
  PERMISSION_REMOVE = 'PERMISSION_REMOVE',


  AUDIT_VIEW = 'AUDIT_VIEW'
}



